libhid: hid_parsing.c File Reference
hid_parsing.c File Reference
#include <hid.h>
#include <hid_helpers.h>
#include <string.h>
#include <debug.h>
#include <assert.h>
Defines
#define HID_INTERNAL
Functions
static void hid_prepare_parse_path (HIDInterface *const hidif, int const path[], unsigned int const depth)
hid_return hid_init_parser (HIDInterface *const hidif)
hid_return hid_prepare_parser (HIDInterface *const hidif)
void hid_reset_parser (HIDInterface *const hidif)
hid_return hid_find_object (HIDInterface *const hidif, int const path[], unsigned int const depth)
hid_return hid_extract_value (HIDInterface *const hidif, unsigned char *const buffer, double *const value)
hid_return hid_get_report_size (HIDInterface *const hidif, unsigned int const reportID, unsigned int const reportType, unsigned int *size)
hid_return hid_format_path (char *const buffer, unsigned int length, int const path[], unsigned int const depth)
Define Documentation
#define HID_INTERNAL
Definition at line 1 of file hid_parsing.c.
Function Documentation
hid_return hid_extract_value (HIDInterface *const hidif, unsigned char *const buffer, double *const value)
Definition at line 143 of file hid_parsing.c.
References ASSERT, ERROR, GetValue(), HIDInterface_t::hid_data, hid_is_opened(), HIDInterface_t::hid_parser, HID_RET_DEVICE_NOT_OPENED, HID_RET_INVALID_PARAMETER, HID_RET_SUCCESS, HIDInterface_t::id, TRACE, and HIDData::Value.
Referenced by hid_get_item_value().
hid_return hid_find_object (HIDInterface *const hidif, int const path[], unsigned int const depth)
Definition at line 117 of file hid_parsing.c.
References ASSERT, ERROR, FindObject(), HIDInterface_t::hid_data, hid_format_path(), hid_is_opened(), HIDInterface_t::hid_parser, hid_prepare_parse_path(), HID_RET_DEVICE_NOT_OPENED, HID_RET_NOT_FOUND, HID_RET_SUCCESS, HIDInterface_t::id, NOTICE, and WARNING.
Referenced by hid_get_feature_report(), hid_get_input_report(), hid_get_item_value(), hid_set_feature_report(), and hid_set_output_report().
hid_return hid_format_path (char *const buffer, unsigned int length, int const path[], unsigned int const depth)
Definition at line 199 of file hid_parsing.c.
References ERROR, HID_RET_INVALID_PARAMETER, HID_RET_OUT_OF_SPACE, HID_RET_SUCCESS, TRACE, and WARNING.
Referenced by hid_find_object().
hid_return hid_get_report_size (HIDInterface *const hidif, unsigned int const reportID, unsigned int const reportType, unsigned int * size)
Definition at line 176 of file hid_parsing.c.
References ASSERT, ERROR, GetReportOffset(), HIDInterface_t::hid_data, hid_is_opened(), HIDInterface_t::hid_parser, HID_RET_DEVICE_NOT_OPENED, HID_RET_INVALID_PARAMETER, HID_RET_SUCCESS, and HIDInterface_t::id.
Referenced by hid_get_item_value().
hid_return hid_init_parser (HIDInterface *const hidif)
Definition at line 31 of file hid_parsing.c.
References ASSERT, ERROR, HIDInterface_t::hid_data, hid_is_opened(), HIDInterface_t::hid_parser, HID_RET_DEVICE_NOT_OPENED, HID_RET_FAIL_ALLOC, HID_RET_SUCCESS, HIDInterface_t::id, NOTICE, and TRACE.
Referenced by hid_prepare_interface().
static void hid_prepare_parse_path (HIDInterface *const hidif, int const path[], unsigned int const depth) [static]
Definition at line 11 of file hid_parsing.c.
References ASSERT, HIDInterface_t::hid_data, hid_is_opened(), HIDInterface_t::id, HIDPath::Node, HIDData::Path, HIDPath::Size, TRACE, HIDNode::UPage, and HIDNode::Usage.
Referenced by hid_find_object().
hid_return hid_prepare_parser (HIDInterface *const hidif)
Definition at line 67 of file hid_parsing.c.
References ASSERT, ERROR, HIDInterface_t::hid_data, hid_is_opened(), HIDInterface_t::hid_parser, hid_reset_parser(), HID_RET_DEVICE_NOT_OPENED, HID_RET_SUCCESS, HIDParse(), HIDInterface_t::id, NOTICE, HIDParser::ReportDesc, HIDParser::ReportDescSize, and TRACE.
Referenced by hid_prepare_interface().
void hid_reset_parser (HIDInterface *const hidif)
Definition at line 105 of file hid_parsing.c.
References ASSERT, ERROR, hid_is_opened(), HIDInterface_t::hid_parser, HIDInterface_t::id, ResetParser(), and TRACE.
Referenced by hid_close(), hid_dump_tree(), and hid_prepare_parser().