libhid: hid_presentation.c File Reference
hid_presentation.c File Reference
#include <hid.h>
#include <hid_helpers.h>
#include <debug.h>
#include <assert.h>
Defines
#define HID_INTERNAL
Functions
hid_return hid_write_identification (FILE *const out, HIDInterface const *const hidif)
hid_return hid_dump_tree (FILE *const out, HIDInterface *const hidif)
const char * hid_strerror (hid_return ret)
Define Documentation
#define HID_INTERNAL
Definition at line 1 of file hid_presentation.c.
Function Documentation
hid_return hid_dump_tree (FILE *const out, HIDInterface *const hidif)
Definition at line 66 of file hid_presentation.c.
References ERROR, HIDInterface_t::hid_data, hid_is_opened(), HIDInterface_t::hid_parser, hid_reset_parser(), HID_RET_DEVICE_NOT_OPENED, HID_RET_INVALID_PARAMETER, HID_RET_SUCCESS, HIDParse(), HIDInterface_t::id, HIDPath::Node, HIDData::Path, HIDPath::Size, TRACE, HIDData::Type, HIDNode::UPage, and HIDNode::Usage.
const char* hid_strerror (hid_return ret)
Definition at line 102 of file hid_presentation.c.
References HID_RET_ALREADY_INITIALISED, HID_RET_DEVICE_ALREADY_OPENED, HID_RET_DEVICE_NOT_FOUND, HID_RET_DEVICE_NOT_OPENED, HID_RET_FAIL_ALLOC, HID_RET_FAIL_CLAIM_IFACE, HID_RET_FAIL_CLOSE_DEVICE, HID_RET_FAIL_DETACH_DRIVER, HID_RET_FAIL_FIND_BUSSES, HID_RET_FAIL_FIND_DEVICES, HID_RET_FAIL_GET_REPORT, HID_RET_FAIL_INT_READ, HID_RET_FAIL_OPEN_DEVICE, HID_RET_FAIL_SET_REPORT, HID_RET_HID_DESC_SHORT, HID_RET_INVALID_PARAMETER, HID_RET_NOT_FOUND, HID_RET_NOT_HID_DEVICE, HID_RET_NOT_INITIALISED, HID_RET_OUT_OF_SPACE, HID_RET_REPORT_DESC_LONG, HID_RET_REPORT_DESC_SHORT, HID_RET_SUCCESS, and HID_RET_TIMEOUT.
hid_return hid_write_identification (FILE *const out, HIDInterface const *const hidif)
Definition at line 9 of file hid_presentation.c.
References HIDInterface_t::dev_handle, HIDInterface_t::device, ERROR, hid_is_opened(), HID_RET_DEVICE_NOT_OPENED, HID_RET_INVALID_PARAMETER, HID_RET_SUCCESS, and HIDInterface_t::id.